/** HERE YOU CAN ADD ALL YOUR ENVIRONMENT VARIABLES */
const DEBUG = process.env.DEBUG || false;
if (DEBUG) {
    console.log('DEBUG ENABLED');
}

const PORT = process.env.PORT || 9000;
const TEST_MODE = process.env.TEST_MODE;
const IMAGE_UPLOAD_SIZE_LIMIT = process.env.IMAGE_UPLOAD_SIZE_LIMIT;
const PRIVATE_KEY =
    'LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBeGs2VVRhMEdUT2g4UmZ1T1kreFVHRTlEdlFCYlVtbE5ZVHlxeXFpQmJ5dmxiM3hECnAyRnBUd3ZLVDZkaWRDMVBRMGhwU2VteVg0Lzg4QjlpeE0xNzBYSkJjMVdTN1VhOGpTcUwySnl1dVY2cVpNTlcKVzdKTXZteHk2QitacTFwWWNybWRoWk9PaEdMTFYrR0ZVTjlLZkFhcUlqaTNwOFBYMkVocytteENUaWgzcGpROApBR0R6NEdsMkVxVWNlZFhNSVpBRzIxMkJsWGp4c0U1U2E5UFhZZVdNUlZyKzlQbTZXaDNrblRDSjlWQ2M5ZUVtClpQdUwzLytJMEpLdmdpeGVldlhCRFVSYVRmZ0dpcjdDMFY5TXJxMndwcFNFcUozR2FpL3dnZGw2ZzhxUi9Rb2QKQmx2a0ROM3BsZE02eTREVThlYWRhc0cwTkRqNjVYdUF3V0VreVFJREFRQUJBb0lCQUhtaVhTaS94aXVLTmgrZQp5cG5UclVrejVUS2FjMms3R2JGWXl0Ri9SZFR3c2N3T0JsazJVS2VoYmJncHpTUEJYdXJBRVlTNmlTUkFaejdKCm9ZVmhIRjg5bTVPb20zUmFmUENCZGtHbzZTcmVPOW1PVHZ2emcwc1JyZkZlNEp6UHo0eWUrVldqU2prOWQ4Z3gKbGRvaSs4YlRONnZCNmpSRzFhL2R6S3BWbU4zaXM3VnR5NjNBVElwckszZHlBMi80L2xVN2NEODJIR0VwOVZOZgpqWEJPaUl0YXloWnVFOFQrTFRXMEFsZEFheGhmR3Bya21LL0VPMGx3Um1haW1kWGNka1B5Y1o0ZTNuTXdpM3pRCmhOV0MweUxWdUNwN2hiUmNoV3JNOTMzM3NvTGw3ZnRRZnFwREgwT25lMElaNHd4alBhUmxIcXJ3d1pkMXhLT3cKVHRuV1pwa0NnWUVBN0pYMDJkem1hdGxVUWNNMU5vb25GazZQZmY2ZkV2d3pUUkJXSVNYd3YyVk9CYVZDanpWQQoyQUhpK0k1UTNFMjVBNXdJZSs0WkhTYVR5UmJKSjhIem14enBiSExMMjZjSFVzWS8zQk9HUHd3ZUxGMitWZCt0Ck4zZHJxajdmRklTM1paNDkxTHNGTzdjWDVNWUpxS0IwNWZ3N3hPWjQreGdnb0pkQllSQWUvSHNDZ1lFQTFwUjgKWEY4amdIYS80VlovSnNSMmx0djRhV2tkbEdUVTlNVWhYYW1FQlFqcHE0ZC8xWFdiTVdxYUVSMVdqTk9WbDlYVgpPc1dSU3BxNlJmUmxjL3JzcUxnVXh5Rm5JWEZXT1dIY1Y0T3VMVE1IeVJBUjdqd2JFMlEyV0VERVhYOCtlUzNQCkFodmVocEIvdEh0OHFHNDdjU3Y4VVRsMVNVcHBKOFRRbFB4dnlvc0NnWUFDdjBjRmxKd1VWNHV6NjhsZFpjTkkKYmdjYWhtOWdjQTlFY05FZk4ycVJQbUxtaStHMitmNVR3OG5YNndjalY3K3pQQWVaTU0yWDJnL1RRUEY3QmJTSApjNUYrVWVMdUhRVm52NmVVTGFIY2I0NldJMHlIZ0w1cEszalRsRUZRNHEyaWYzRG1YSG1XRk8weEdkK1kxcXdrCjA0WDZKbGIzUzNOdGlmUVhaWEdHcXdLQmdRQ1JteXFVSjc3WWNqd2NOV3lNcXUzcHlwUlRPdy9tWFZHZ1VwQWsKbFYzUGFNL2ZKRkFiVWZXZ1g3eng5aDEvN0Nkclk1K1FoUFhsVVA4cmJ2N1U1NlZsaTV3Vno5WENmTHpNclZvdQpURjJKc0VJTkxvbHNSbjc4OXBobDVIVWJHTGdVMUgvTzU0aGxlWEllejFpMGxqQmh5RDRzQTdoUnBsdWFyOVAxCjlTSUtwd0tCZ1FEVWE3RVc5N3VjeStQWlJwSlZZaDYyRUVaQ0x6SEp6cW8vN0ZmdVlpQXhrczRzcEVBajNSd0gKOTA1MkdKRUdGNzh0SVRkYStLdVovYW5BOWR5NTJ6QlBjSmVnZTcrTWpSZjVqREpqVjZsRGxKVHFHWHN6bFdocgo3OXFUdUFpZVNsR0pIK3FIbU1GUUEyeldYWlE5T1BUK0hhNUNUMThWVHJTTG5kRWxjKzQ2Nnc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=';
const PUBLIC_KEY =
    'LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF4azZVVGEwR1RPaDhSZnVPWSt4VQpHRTlEdlFCYlVtbE5ZVHlxeXFpQmJ5dmxiM3hEcDJGcFR3dktUNmRpZEMxUFEwaHBTZW15WDQvODhCOWl4TTE3CjBYSkJjMVdTN1VhOGpTcUwySnl1dVY2cVpNTldXN0pNdm14eTZCK1pxMXBZY3JtZGhaT09oR0xMVitHRlVOOUsKZkFhcUlqaTNwOFBYMkVocytteENUaWgzcGpROEFHRHo0R2wyRXFVY2VkWE1JWkFHMjEyQmxYanhzRTVTYTlQWApZZVdNUlZyKzlQbTZXaDNrblRDSjlWQ2M5ZUVtWlB1TDMvK0kwSkt2Z2l4ZWV2WEJEVVJhVGZnR2lyN0MwVjlNCnJxMndwcFNFcUozR2FpL3dnZGw2ZzhxUi9Rb2RCbHZrRE4zcGxkTTZ5NERVOGVhZGFzRzBORGo2NVh1QXdXRWsKeVFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==';

const OPENAI_API_KEY = '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';
const CLOUD_NAME = 'deye3gicq';
const CLOUDINARY_API_KEY = '824696885955381';
const CLOUDINARY_API_SECRET = 'rRS6znH_5wvEhcZzUYZNqi7zXt0';
const CLOUDINARY_API_ENV =
    'CLOUDINARY_URL=cloudinary://824696885955381:rRS6znH_5wvEhcZzUYZNqi7zXt0@deye3gicq';
const SECRET = 'another_private_secret_seriously';
const GOOGLE_CLIENT_ID =
    process.env.GOOGLE_CLIENT_ID ||
    '518559658778-c2p6o5vmg7avqdqkghtd5p8nsa2keb3o.apps.googleusercontent.com';
const GOOGLE_CLIENT_SECRET =
    process.env.GOOGLE_CLIENT_SECRET || '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';
const GOOGLE_CALLBACK_URL =
    process.env.GOOGLE_CALLBACK_URL ||
    'http://localhost:3000/oauth2/redirect/google';
const DATABASE_URL = 'postgres://postgres:Monica@7029!@localhost:5432/kikao';
const JWT_SECRET = process.env.JWT_SECRET || 'ChiziKarogwaTena';
const NODE_ENV = process.env.NODE_ENV || 'development';
const FRONTEND_APP_LOGIN_REDIRECT =
    process.env.FRONTEND_APP_LOGIN_REDIRECT ||
    'http://localhost:9001/login/success';

interface EnvVariables {
    PORT: number;
    debug: boolean;
    IMAGE_UPLOAD_SIZE_LIMIT: number;
    FRONTEND_APP: string;
    TEST_MODE: boolean;
    PUBLIC_KEY: string;
    PRIVATE_KEY: string;
    OPENAI_API_KEY: string;
    CLOUDINARY_API_SECRET: string;
    CLOUDINARY_API_KEY: string;
    CLOUD_NAME: string;
    CLOUDINARY_API_ENV: string;
    DATABASE_URL: string;
    SECRET: string;
    NODE_ENV: 'development' | 'production' | 'test';
    JWT_SECRET: string;
    GOOGLE_CLIENT_ID: string;
    GOOGLE_CLIENT_SECRET: string;
    GOOGLE_CALLBACK_URL: string;
}

// Make sure to add your env variables to this object so that they are exported to the rest of the application
const env = {
    PORT: PORT,
    debug: DEBUG,
    IMAGE_UPLOAD_SIZE_LIMIT: Number(IMAGE_UPLOAD_SIZE_LIMIT!),
    FRONTEND_APP_LOGIN_REDIRECT: FRONTEND_APP_LOGIN_REDIRECT,
    TEST_MODE: TEST_MODE,
    PUBLIC_KEY: PUBLIC_KEY,
    PRIVATE_KEY: PRIVATE_KEY,
    OPENAI_API_KEY: OPENAI_API_KEY,
    CLOUDINARY_API_SECRET: CLOUDINARY_API_SECRET,
    CLOUDINARY_API_KEY: CLOUDINARY_API_KEY,
    CLOUD_NAME: CLOUD_NAME,
    CLOUDINARY_API_ENV: CLOUDINARY_API_ENV,
    DATABASE_URL: DATABASE_URL,
    SECRET: SECRET,
    NODE_ENV: NODE_ENV,
    JWT_SECRET: JWT_SECRET,
    GOOGLE_CLIENT_ID: GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: GOOGLE_CLIENT_SECRET,
    GOOGLE_CALLBACK_URL: GOOGLE_CALLBACK_URL
};

export default env;
